version: '3.8'

services:
  mysql:
    container_name: mysql
    image: harvest-mysql:latest
    restart: always
    env_file:
      # A value for MYSQL_ROOT_PASSWORD must be supplied
      - ./mysql/env/docker-root.env
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql:/var/lib/mysql
  api:
    container_name: api
    image: harvest-api:latest
    restart: always
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      ENV: "docker"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    
volumes:
  mysql: