#!/bin/bash


app_location="cmd/harvest/main.go"

install () {
	go mod download && go mod verify
}

build () {
	go build -o runner $app_location $@
}

run () {
	build
	./runner
}

test () {
	go test -v $(go list ./tests/... | grep -v /mocks) -coverpkg $(go list ./pkg/... | grep -v /app) $@
}

$@