#!/bin/bash


app_location="cmd/harvest/main.go"

install () {
	go mod download && go mod verify
}

build () {
	runner () {
		go build -o runner $app_location $@
	}
	
	docker () {
		docker build . $@
	}

	$@
}

run () {
	go run $app_location $@
}

dev () {
	reflex -s -g reflex.conf -- reflex -c reflex.conf
	reflex -c ./reflex.conf $@
}

lint () {
	golangci-lint run --issues-exit-code 0 $@
}

format () {
	lint --fix $@
}

$@