#!/bin/bash


app_location="cmd/harvest/main.go"

build () {
	swag init --parseDependency -g ./$app_location $@
	go build -o server $app_location $@
}

run () {
	build
	./server
}

test () {
	go test -v $(go list ./tests/... | grep -v /mocks) -coverpkg $(go list ./pkg/... | grep -v /app) $@
}

$@